api = "0.5"

[buildpack]
id = "fagiani/s3-tarball"
version = "0.1.11"
name = "S3 Tarball Cloud Native Buildpack"
homepage = "https://github.com/fagiani/s3-tarball-buildpack"
description = "Downloads and writes files within tarballs from private S3 buckets in build time"
keywords = ["S3", "tar", "tarball", "tgz", "archives", "build", "write", "external", "files"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
